# Generated by Django 3.2.8 on 2021-10-18 08:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='image_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 18, 8, 5, 48, 247251, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default=datetime.datetime(2021, 10, 18, 8, 6, 52, 152905, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=60)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
